### ISSUE TITLE
div moving, invisible buttons on the full screen, window size

### ISSUE THREAD

**Issue by brandart** [rstropek-teaching/real-time-game-quiz-4ahif-brandart#1]
### 1. Problem
my bars are in a div and when I want to move these divs i use: 
`$('#footer').animate({
            'marginLeft': "-=30px" //moves left
        });`
but this is very slow and inefficient, is there a better solution?

the full div is like this:
`<div id="footer" style="text-align: center;">
        <svg width="200" height="50">
            <rect width="200" height="50" style="fill: #FFFFFF" />
        </svg>
    </div>`

### 2. Problem
I don't know how I can make invisible buttons that are running over the full screen

![](https://user-images.githubusercontent.com/31988348/34222041-777fb09c-e5ba-11e7-87e5-b507f4f00b91.png)

and is there a cool solution where the bar moves faster, the longer I touch the screen (the buttons?), 
For now I use an index, which moves the bar after pressing some basic buttons

### 3. Problem
I want the game on my iPhones, therefore I always look, how it would look on a e.g iPhone 7 in the browser,

but how can I get the size of the window (iPhone), because the bars, shouldn't move outside the window, right?

### PS
I like this homework, it's lot to do, but I think it totally improve my basic programming skills 
:+1:

**Comment by rstropek** [comment]
Hi @brandart 

Thank you for your email. Let me start with a tip: If you want others to contribute code or tips to your projects, try to make your project as easy to compile and test as possible. I recommend adding appropriate scripts to *package.json* with which a contributor can build and run your app. However, I found my way through ;-)

To your question:

* I recommend that you use a single *svg* element for your entire game. Do not split your SVG code in mulitple *div*s.
* Do not move the *div*s. Move the SVG elements instead. The library *snapsvg* has very nice features for that (see [this example](http://svg.dabbles.info/snaptut-load-animate)).
* Concerning screen size: Try guides like [this](http://ryanve.com/lab/dimensions/). You can open them on your iPhone and check whether the result is as expected.

Does that help?

Greetings,
Rainer Stropek.
