### ISSUE TITLE
TypeError: Cannot read property 'docs' of undefined

### ISSUE THREAD

**Issue by brandart** [rstropek-teaching/real-time-game-quiz-4ahif-brandart#3]
I am using CouchDB to save the username and the score for the game.

And now I am trying to create a new user if a new user log in:

$('#sendUsername').click(function () {
        if (!$('#username').val()) {
            alert("Parameters missing!");
        } else {
            let selector = {
                "selector": {
                    "name": { "$eq": <string>$('#username').val() },
                },
                "fields": ["name"]
            };
            let data = doPost(selector, "http://127.0.0.1:5984/pong/_find");

            if(data.docs[0] != undefined){
                alert("already");
            }else{
                let newUser = {
                    "name": <string>$('#username').val(),
                    "score": 0
                }
                let dataPost = doPost(newUser, "http://127.0.0.1:5984/pong/");
                if(dataPost != undefined){
                    alert("User created");
                }
            }
            socket.emit('userConnect');
        }

    });`

and the doPost method looks like this:
`function doPost(object: any, searchUrl: string): any {
        let returnData: any;
        $.ajax({
            type: "POST",
            url: searchUrl,
            contentType: "application/JSON",
            data: JSON.stringify(object),
            dataType: "json",
            async: false,
            success: function (data) {
                returnData = data;
            }
        });
        return returnData;
    }`

and I get _Uncaught (in promise) TypeError: Cannot read property 'docs' of undefined_ message when I am in this line: 

`if(data.docs[0] != undefined){`

the **searchUrl** is correct, I have already tried it with postman, works fine

**Comment by rstropek** [comment]
Hi @brandart 

I think you have a timing problem. In your `doPost` method, you call `$.ajax`. In that call, you provide a callback (`success` function) that will be called one the AJAX call will finish. However, you return and process `returnData` immediately after you **started** `doPost`. At that time, the AJAX call is not finished -> `returnData` is `undefined` -> error.

You have to following options to fix your project:

* Add a callback parameter to `doPost`. Call the callback once the AJAX call is finished (i.e. in the `success` function).
* Make your `doPost` function return a *Promise* and use `async/await` when calling it.
* Simplest solution: Don't create a separate function `doPost` and call `$.ajax` directly.

If you cannot fix the problem based on this tips, check in your code. I will try to change it so you see how you can make it work.

Greetings,
Rainer Stropek.

**Comment by brandart** [comment]
Hello @rstropek 

I checked in my code, because I couldn't fix this problem.
I would be very thankful, if you could help me,

Greetings,
Arthur Brandstetter.

**Comment by rstropek** [comment]
Hi @brandart 

No problem. I just checked in a few lines of code that demonstrate how to correctly return a `Promise`.

Note that I also extended your *package.json* file. I now has scripts for building and starting the project. Whenever you want other people to contribute to your code, you should offer such helper scripts.

Do my code changes help?

Greetings,
Rainer Stropek.

**Comment by brandart** [comment]
Hello,

where do I see this lines of code? I can't find it.
Did you commit? 

Greetings,
Arthur Brandstetter.

**Comment by rstropek** [comment]
Ups, sorry. I committed but I did not push my changes to GitHub. Thank you for reminding me. Now you should see it.

**Comment by brandart** [comment]
Ok thanks for the code,

I don't get the undefined error anymore, but now I recieve an POST http://127.0.0.1:5984/pong/_find 415 (Unsupported Media Type) Error 

What's wrong in my code? 

Is there any problem with the doPost function?

**Comment by rstropek** [comment]
You want to access CouchDB, right? Try to build the HTTP POST request to `_find` in a REST client like *Postman*. Make sure that it works there. Next, compare the HTTP POST that your program sends (e.g. using Chrome's Developer Tools) with the successful request in Postman. Pay special attention to the HTTP headers! Do you find any differences?

Let me know if this tip helps.

Greetings,
Rainer Stropek.

**Comment by brandart** [comment]
Finally I found the problem 👍 

in my doPost I had: `contentType: "application/JSON",`

and I needed `contentType: "application/json",`

Thanks!
Greetings,
Arthur Brandstetter.
